---
title: "Compulsory Exercise 2: Prediction of Alzheimers Disease from Longitudinal MRI Data"
author:
- Chester Henry Charlton
- Kasper Eikeland
- Tinus Garshol
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes: \usepackage{amsmath}
output:
  html_document:
  #   toc: no
  #   toc_depth: '2'
  #   df_print: paged
  #pdf_document:
    toc: no
    toc_depth: '2'
urlcolor: blue
abstract: "This is the place for your abstract (max 350 words)"
---
  
```{r setup, include=FALSE}
library("knitr")
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,message=FALSE,warning=FALSE,strip.white=TRUE,prompt=FALSE, # nolint
                      cache=TRUE, size="scriptsize",fig.width=4, fig.height=3,fig.align = "center")

```

```{r,eval=TRUE,echo=FALSE}
library("rmarkdown")
library("dplyr")
library("GGally")
library("tidyr")
library("formatR")
```

```{r}
#setwd("/Users/chcharlton/NTNU/statLearning/compulsory_alzheimers")
#setwd("/Users/kaspe/Documents/NTNU/23V/TMA4268_Statistical_Learning/Projects/tma4268_alzheimers")
setwd("C:/Users/tinus/OneDrive/Desktop/GitHub/tma4268_alzheimers")
```


```{r}
longitudinal.df <- read.csv("oasis_longitudinal.csv")
cross_sectional.df <- read.csv("oasis_cross-sectional.csv")
```

<!--  Henry's initial work here -->


<!--  Kasper's initial work here. -->
```{r}

# Patient is demented if CDR is > 0
cs_mutated <- cross_sectional.df %>%
  dplyr::select(c(M.F, eTIV, nWBV, ASF, Age, CDR)) %>%
  na.omit() %>%
  mutate(Demented = as.factor(CDR>0),
         M.F = as.factor(M.F))

longitudinal.df <- read.csv("oasis_longitudinal.csv")

longitudinal_deltas <- longitudinal.df %>% 
  group_by(Subject.ID) %>%
  summarise(dMMSE = (last(MMSE) - first(MMSE)) / last(Visit), 
            deTIV = (last(eTIV) - first(eTIV)) / last(Visit),
            dnWBV = (last(nWBV) - first(nWBV)) / last(Visit),
            dASF = (last(ASF) - first(ASF)) / last(Visit),
            dAge = (last(Age) - first(Age)) / last(Visit))

baseline_with_deltas <- longitudinal.df %>%
  filter(Visit == 1) %>%
  left_join(longitudinal_deltas, by = c("Subject.ID")) %>%
  mutate(Demented = as.factor(Group != "Nondemented"), # Those who converted became demented
         M.F = as.factor(M.F)) %>% 
  dplyr::select(-c(Subject.ID, MRI.ID, Group, Visit, MR.Delay, Hand, CDR, SES)) 
  
# cross-sectional data
ggpairs(cs_mutated)

# longitudinal data
ggpairs(baseline_with_deltas)
```

```{r}
library("tree")
library("gbm")
library("randomForest")


set.seed(1337)
# Longitudinal data
train <- sample(1:nrow(baseline_with_deltas), floor(.75 * nrow(baseline_with_deltas)))
longitudinal.train <- na.omit(baseline_with_deltas[train,])
longitudinal.test <- na.omit(baseline_with_deltas[-train,])
```


```{r}
# Classification tree
set.seed(1337)
longitudinal.tree <- tree(Demented ~., longitudinal.train)
summary(longitudinal.tree)
plot(longitudinal.tree)
text(longitudinal.tree, pretty = 0)

# Test predictions
pred.tree <- predict(longitudinal.tree, newdata=longitudinal.test, type = "class")
table(pred = pred.tree, truth = longitudinal.test$Demented) # 0.7837838
# Pruning?
```


```{r}
# Bagging
set.seed(1337)
longitudinal.bag <- randomForest(Demented ~., longitudinal.train, mtry = 12, importance = TRUE)
summary(longitudinal.bag)
plot(longitudinal.bag)
yhat.bag <- predict(longitudinal.bag, newdata = longitudinal.test, type = "class")
table(pred = yhat.bag, truth = longitudinal.test$Demented) # 0.8648649
```


```{r}
# Random forest
set.seed(1337)
longitudinal.rf <- randomForest(Demented ~., longitudinal.train, importance = TRUE)
summary(longitudinal.rf)
plot(longitudinal.rf)
yhat.rf <- predict(longitudinal.rf, newdata = longitudinal.test, type = "class")
table(pred = yhat.rf, truth = longitudinal.test$Demented) # 0.8108108
```


```{r}
# Boosting
set.seed(1337)
longitudinal.train.boost <- mutate(longitudinal.train, Demented = ifelse(Demented == "FALSE", 0,1))
longitudinal.boost <- gbm(Demented ~., data = longitudinal.train.boost, 
                          distribution = "bernoulli", n.trees = 5000, interaction.depth = 2)
summary(longitudinal.boost)
longitudinal.test.boost <- mutate(longitudinal.test, Demented = ifelse(Demented == "FALSE", 0,1))
<<<<<<< Updated upstream
yhat.boost <- predict(longitudinal.boost, newdata = longitudinal.test.boost, n.trees = 5000, type = "response")
yhat.boost <- ifelse(yhat.boost > 0.5, 1,0)
table(pred = yhat.boost, truth = longitudinal.test.boost$Demented) # 0.8648649
=======
yhat.boost <- predict(longitudinal.boost, newdata = longitudinal.test.boost, n.trees = 1000, type = "response")
yhat.boost <- ifelse(yhat.boost > 0.5, 1,0) # nolint
table(yhat.boost, longitudinal.test.boost$Demented)
>>>>>>> Stashed changes
```


```{r}
# Logistic
longitudinal.logistic <- glm(Demented ~., family = binomial, data = longitudinal.train)
logistic.probs <- predict(longitudinal.logistic, newdata = longitudinal.test, type = "response")
yhat.logistic <- ifelse(logistic.probs > .5, 1,0)
table(pred = yhat.logistic, truth = longitudinal.test$Demented) # 0.8648649

```


```{r}
# SVM
install.packages("e1071")
library("e1071")

# Linear kernel
lin.svm <- svm(Demented~.,data=longitudinal.train,kernel="linear",cost=10)
lin.svm.predict <- predict(lin.svm,newdata=longitudinal.test,type="class")
table(lin.svm.predict,longitudinal.test$Demented)

# Polynomial kernel
pol.svm <-svm(Demented~.,data=longitudinal.train,kernel="polynomial",cost=10)
pol.svm.predict <- predict(pol.svm,newdata=longitudinal.test,type="class")
table(pol.svm.predict,longitudinal.test$Demented)

# Radial kernel
rad.svm <-svm(Demented~.,data=longitudinal.train,kernel="radial",cost=10)
rad.svm.predict <- predict(rad.svm,newdata=longitudinal.test,type="class")
table(rad.svm.predict,longitudinal.test$Demented)

# Sigmoid kernel
sig.svm <-svm(Demented~.,data=longitudinal.train,kernel="sigmoid",cost=10)
sig.svm.predict <- predict(sig.svm,newdata=longitudinal.test,type="class")
table(sig.svm.predict,longitudinal.test$Demented)

# Testing the different kernels for different costs "C"

C = c(1:20)
miss_lin = c()
miss_pol = c()
miss_rad = c()
miss_sig = c()
for (i in 1:length(C)) {
  test_lin.svm <- svm(Demented~.,data=longitudinal.train,kernel="linear",cost=C[i])
  test_pol.svm <- svm(Demented~.,data=longitudinal.train,kernel="polynomial",cost=C[i])
  test_rad.svm <- svm(Demented~.,data=longitudinal.train,kernel="radial",cost=C[i])
  test_sig.svm <- svm(Demented~.,data=longitudinal.train,kernel="sigmoid",cost=C[i])
  test_lin.svm.predict <- predict(test_lin.svm,newdata=longitudinal.test,type="class")
  test_pol.svm.predict <- predict(test_pol.svm,newdata=longitudinal.test,type="class")
  test_rad.svm.predict <- predict(test_rad.svm,newdata=longitudinal.test,type="class")
  test_sig.svm.predict <- predict(test_sig.svm,newdata=longitudinal.test,type="class")
  tab_lin <- table(test_lin.svm.predict,longitudinal.test$Demented)
  tab_pol <- table(test_pol.svm.predict,longitudinal.test$Demented)
  tab_rad <- table(test_rad.svm.predict,longitudinal.test$Demented)
  tab_sig <- table(test_sig.svm.predict,longitudinal.test$Demented)
  miss_lin <- c(miss_lin,tab_lin[1,2]+tab_lin[2,1])
  miss_pol <- c(miss_pol,tab_pol[1,2]+tab_pol[2,1])
  miss_rad <- c(miss_rad,tab_rad[1,2]+tab_rad[2,1])
  miss_sig <- c(miss_sig,tab_sig[1,2]+tab_sig[2,1])
}
plot(C,miss_lin)
plot(C,miss_pol)
plot(C,miss_rad)
plot(C,miss_sig)

long.svm <- svm(Demented~.,data=longitudinal.train)
long.svm.predict <- predict(long.svm,newdata=longitudinal.test,type="class")
table(long.svm.predict,longitudinal.test$Demented)
summary(long.svm)



```


```{r}
# LDA
library("MASS")

longitudinal.lda <- lda(Demented ~ ., data = longitudinal.train)
yhat.lda <- predict(longitudinal.lda, newdata = longitudinal.test)$class
table(pred = yhat.lda, truth = longitudinal.test$Demented) # 0.8108108

```


```{r}
# QDA
longitudinal.qda <- qda(Demented ~ ., data = longitudinal.train)
yhat.qda <- predict(longitudinal.qda, newdata = longitudinal.test)$class
table(pred = yhat.qda, truth = longitudinal.test$Demented) # 0.8648649
```



<!--  Tinus' initial work here. -->



## Introduction: Scope and purpose of your project


## Descriptive data analysis/statistics
```{r}
summary(baseline_with_deltas)

hist(baseline_with_deltas$Demented~baseline_with_deltas$dAge)
```

## Methods


## Results and interpretation


## Summary
